blank_issues_enabled: true
contact_links:
  - name: SMAIRT Documentation
    url: https://github.com/biodataganache/smairt-cookiecutter#readme
    about: Check the README for usage instructions and philosophy
